import React, { useState } from 'react';
import { Check, X, MessageSquare, AlertCircle, CheckSquare } from 'lucide-react';
import toast from 'react-hot-toast';
import apiClient from '../api/apiClient';

// Mock Approvals Data
const mockApprovals = [
  { id: 'app_1', leadName: 'Sarah Connor', requestedBy: 'John Agent', date: '2023-11-01T10:00:00Z', status: 'pending', type: 'Special Discount' },
  { id: 'app_2', leadName: 'Kyle Reese', requestedBy: 'Jane Agent', date: '2023-11-02T14:30:00Z', status: 'pending', type: 'Custom AI Prompt' },
  { id: 'app_3', leadName: 'T-800', requestedBy: 'John Agent', date: '2023-10-28T09:15:00Z', status: 'approved', type: 'Extended Trial' },
];

const Approvals: React.FC = () => {
  const [approvals, setApprovals] = useState(mockApprovals);
  const [activeTab, setActiveTab] = useState<'all'|'pending'|'approved'|'rejected'>('pending');
  const [showModal, setShowModal] = useState(false);
  const [activeApproval, setActiveApproval] = useState<any>(null);
  const [actionType, setActionType] = useState<'approve'|'reject'|null>(null);
  const [comment, setComment] = useState('');

  const handleActionClick = async (approval: any, action: 'approve'|'reject') => {
    if (action === 'approve') {
      try {
        await apiClient.put(`/approvals/${approval.id}`, { status: 'approved' });
      } catch (err) {
        console.warn("API unavailable, mock fallback", err);
      }
      setApprovals(approvals.map(app => 
        app.id === approval.id ? { ...app, status: 'approved' } : app
      ));
      toast.success('Approval approved successfully.');
      window.dispatchEvent(new CustomEvent('approvals-updated', { detail: -1 }));
    } else {
      setActiveApproval(approval);
      setActionType('reject');
      setComment('');
      setShowModal(true);
    }
  };

  const confirmAction = async () => {
    try {
      await apiClient.put(`/approvals/${activeApproval.id}`, { status: 'rejected', comment });
    } catch (err) {
      console.warn("API unavailable, mock fallback", err);
    }
    setApprovals(approvals.map(app => 
      app.id === activeApproval.id ? { ...app, status: 'rejected' } : app
    ));
    toast.success('Approval rejected successfully.');
    window.dispatchEvent(new CustomEvent('approvals-updated', { detail: -1 }));
    setShowModal(false);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <CheckSquare className="w-6 h-6 text-warning" />
            Pending Approvals
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Review and manage admin requests generated by agents.</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200 dark:border-gray-700 mb-6">
        <nav className="-mb-px flex space-x-8">
          {(['all', 'pending', 'approved', 'rejected'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`
                whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm capitalize
                ${activeTab === tab 
                  ? 'border-blue-500 text-blue-600 dark:text-blue-400 dark:border-blue-400' 
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:hover:text-gray-300 dark:hover:border-gray-600'}
              `}
            >
              {tab}
            </button>
          ))}
        </nav>
      </div>

      <div className="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700">
        <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead className="bg-gray-50 dark:bg-gray-800/80">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Request Type</th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Lead Name</th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Requested By</th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Date</th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
              <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            {approvals.filter(a => activeTab === 'all' || a.status === activeTab).map((approval) => (
              <tr key={approval.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                  {approval.type}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {approval.leadName}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {approval.requestedBy}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                  {new Date(approval.date).toLocaleDateString()}
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full capitalize
                    ${approval.status === 'pending' ? 'bg-warning/20 text-warning dark:text-yellow-400' : 
                      approval.status === 'approved' ? 'bg-success/20 text-success' : 'bg-danger/20 text-danger'}`}>
                    {approval.status}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
                  {approval.status === 'pending' && (
                    <>
                      <button onClick={() => handleActionClick(approval, 'approve')} className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 shadow-sm">
                        <Check className="w-4 h-4 mr-1" /> Approve
                      </button>
                      <button onClick={() => handleActionClick(approval, 'reject')} className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 shadow-sm">
                        <X className="w-4 h-4 mr-1" /> Reject
                      </button>
                    </>
                  )}
                  {approval.status !== 'pending' && (
                    <span className="text-gray-400 italic text-xs">Action taken</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Action Modal */}
      {showModal && activeApproval && (
        <div className="fixed z-50 inset-0 overflow-y-auto flex items-center justify-center min-h-screen px-4">
          <div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" onClick={() => setShowModal(false)}></div>
          <div className="relative z-10 w-full max-w-lg bg-white dark:bg-gray-800 rounded-lg shadow-xl overflow-hidden transform transition-all">
            <div className="bg-white dark:bg-gray-800 px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
              <div className="sm:flex sm:items-start">
                <div className={`mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full sm:mx-0 sm:h-10 sm:w-10 bg-red-100 dark:bg-red-900/30`}>
                  <AlertCircle className="h-6 w-6 text-red-600 dark:text-red-400" />
                </div>
                <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
                  <h3 className="text-lg leading-6 font-medium text-gray-900 dark:text-white" id="modal-title">
                    Reject Request
                  </h3>
                  <div className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                    <p>You are about to reject the <strong>{activeApproval.type}</strong> request for <strong>{activeApproval.leadName}</strong>.</p>
                    
                    <div className="mt-4">
                      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Add a comment (optional)</label>
                      <textarea
                        rows={3}
                        className="shadow-sm focus:ring-red-500 focus:border-red-500 block w-full sm:text-sm border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white p-2 border"
                        placeholder="Your reasoning..."
                        value={comment}
                        onChange={(e) => setComment(e.target.value)}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-gray-50 dark:bg-gray-700/50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse border-t border-gray-200 dark:border-gray-700">
              <button type="button" onClick={confirmAction} className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 text-base font-medium text-white sm:ml-3 sm:w-auto sm:text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 bg-red-600 hover:bg-red-700 focus:ring-red-500">
                Confirm Reject
              </button>
              <button type="button" onClick={() => setShowModal(false)} className="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 dark:border-gray-600 shadow-sm px-4 py-2 bg-white dark:bg-gray-800 text-base font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Approvals;
